### ISSUE TITLE
Bug in visualizer and Shortcuts

### ISSUE THREAD

**Issue by TechnoFynch** [SafehouseCT/ClockWorld-for-Rainmeter#1]
Whenever I restart Spotify, the visualizer will automatically launch even if I have disabled it from Rainmeter and from settings as well. Sometimes even when the visualizer is enabled and showing on the screen, when I check the settings it shows disabled it shows enabled when the visualizer of disabled (shown in the image attached).
Another thing is that I am not able to change the size of the shortcuts line. There are 9 of them by default and I want only seven, but nothing happens when I select 7 from the settings.
![image](https://user-images.githubusercontent.com/44270163/115136846-0f4d3000-a040-11eb-9470-ebee01ad5b9f.png)

**Comment by stenakis** [comment]
Thank you for reaching out to me,
After observing these bugs, I came up with a solution for both of them and
the fix will be available in a couple days.
If you face any other issues let me know.
Evans

>
